/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package training.java.app;

public class App {
    public static void main(String[] args) {
        System.out.println("App running...!");
        System.out.println(MessageUtils.getMessage());
    }
}
