spring:
  jpa:
    properties:
      show-sql: true
      generate-ddl: true
      hibernate:
        hbm2ddl:
          auto: create
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
      database: postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgresql
    url: jdbc:postgresql://localhost:5432/ofonedb
    username: postgres
    password: admin