spring:
  jpa:
#    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
#        format_sql: true
        ddl-auto: create
#        hbm2ddl:
#          auto: update
        dialect: org.hibernate.dialect.MySQL8Dialect
      database: mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/training?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: admin
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-version: 1.0.0

logging:
  level:
    org.hibernate: INFO